filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log

setup.template.name: "nginx-filebeat"
setup.template.pattern: "nginx-filebeat-*"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "nginx-filebeat-%{+yyyy.MM.dd}"


